ExitExamPreparationPlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include 

admin.site.site_header = "Exit Exam Preparation Platform "
admin.site.site_title = "Exit Exam Preparation platform"
admin.site.index_title = "Exit Exam Preparation Platform  Admin"
from accounts.views import mylogin 

urlpatterns = [
  path("", include("home.urls")),
  path("accounts/", include(("accounts.urls",'account'),namespace='account')),
  path("accounts/", include("django.contrib.auth.urls")), 
  path('students/',include("student.urls")),
  path('instructors/',include('instructor.urls')),
  path("admin/login/", mylogin, name="login"), 
  path('admin/', admin.site.urls),
  path('ckeditor/',include('ckeditor_uploader.urls')),
  path('imagefit/', include('imagefit.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include 
from . import views  
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView

urlpatterns = [
  path("signup/", views.signup, name="signup"),
  path("logout/", views.mylogout, name="logout"), 
  path("login/", views.mylogin, name="login"),
  path("profile_edit", views.profileEdit, name="profileEdit"), 
  path("view_profile/", views.viewProfile,name="profile_view" ),
  path('password_reset/', views.ResetPasswordView.as_view(),name="password_reset"), 
  path('password_reset/done/',PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
       name="password_reset_done"),
   path('password-reset-confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'), 
  path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
  path("signup/check_username/", views.check_username, name="check_username"),
   path("signup/check_email/", views.check_email, name="check_email"),
   path("signup/check_password/",views.check_password,name="check_password"), 
   
]

home/urls.py
from django.urls import path, include 
from . import views 

urlpatterns = [
   path("", views.home, name="home"),
   path("about/", views.about, name="about"), 
  
]

student/urls.py
from django.urls import path, include, re_path 
from . import views 

urlpatterns =[

    path("", views.dashboard, name="student_dashboard"),
    path("fetch/all/", views.fetch, name="fetch"),
    path("fetch/courses/<str:status>/", views.courses, name="courses"),
    path("fetch/course/<int:pk>/", views.get_course, name="course"), 
    path("fetch/modules/<int:pk>/<int:course_id>/", views.get_module, name="module"),
    path("fetch/pages/<int:pk>/", views.get_page, name="page"),
    path("pageCompletion/<int:pk>/<str:complete>/", views.page_complete, name="page_complete"),
    path("alpine/", views.alpine, name="alpine"),   
    path("fetch/models/", views.get_models_all,name="all_models"), 
    path("fetch/models/<int:id>/", views.get_models, name="models"), 
    path("fetch/models/<str:view>/", views.get_model_view, name="model_view"),
    path("fetch/tests/", views.get_tests,name="tests"),
    path("fetch/tests/<slug:slug>/",views.course_tests, name="course_tests"), 
    path("take/exam/test/<int:test_id>/", views.take_test_exam, name="take_test"), 
    path("take/exam/test/answer/<int:test_id>/<int:q_id>/<slug:slug>/", views.exam_test_answer, name="test_answer"), 
    path("take/exam/test/next_question/<int:test_id>/<int:q_id>/", views.exam_test_next_question, name="next_test_question"), 
    path("take/exam/model/<int:model_id>/", views.take_model_exam, name="take_model"), 
    path("take/exam/model/answer/<int:model_id>/<int:q_id>/<slug:slug>/", views.exam_model_answer, name="model_answer"), 
    path("take/exam/model/next_question/<int:model_id>/<int:q_id>/", views.exam_model_next_question, name="next_model_question"), 
    path("models/", views.models, name="models"),
    path("modules/", views.modules, name="modules"),
    path("pages/",views.pages, name="pages"),
    path("cppages/", views.cppages, name="cp_pages"),
    path("questions/", views.questions, name="questions"), 
    path("tests/",views.tests, name="test"), 

]

student/models.py
from django.db import models

# Create your models here.

student/views.py
from django.shortcuts import render, get_object_or_404 
from django.http import HttpResponse 
from accounts.models import User 
from EECommittee.models import Course, Department 
from instructor.models import Module, Page, Exam_Model, Test, PageCompletion, ModelQuestion, TestQuestion 
from django.contrib.auth.decorators import login_required 
from django.http import HttpResponse, JsonResponse  
from instructor.models import CourseProgress 
from django.template.defaultfilters import slugify 
from instructor.models import ExamResult, ExamStatus   
from django.contrib import messages 

# Create your views here.

@login_required
def dashboard(request):
    
        print(User.objects.all())
        modelsExams = Exam_Model.objects.filter(dept__name="computer science") 

        return render(request, 'student/index.html',{'users':User.objects.all(),"modelExam":modelsExams})

login_required
def fetch(request): 
      user = request.user 
      print(user.department) 
      courses = Course.objects.all().filter(dept=request.user.department)  
      modelExams = Exam_Model.objects.filter(dept=request.user.department)
      models = []
      for model in modelExams:
           hard = ModelQuestion.objects.filter(modeExam=model,question_type="hard").all().count() or 0
           medium = ModelQuestion.objects.filter(modeExam=model,question_type="medium").count()  or 0
           easy = ModelQuestion.objects.filter(modeExam=model,question_type="easy").count() or 0

           models.append([model,{
                 "hard":hard,
                "medium": medium,
                "easy":easy
           }])
          # models.append(model)
      tests = []
      for course in courses:
           c_tests = Test.objects.filter(course=course)
           for test in c_tests:
               hard = TestQuestion.objects.filter(testExam=test,question_type="hard").all().count() or 0
               medium = TestQuestion.objects.filter(testExam=test,question_type="medium").all().count() or 0
               easy = TestQuestion.objects.filter(testExam=test,question_type="easy").all().count() or 0 

               tests.append([test,course.name,{
                "hard":hard,
                "medium":medium,
                "easy":easy
               }])
           
          #  tests.append(c_tests)
      
      courses_progress= [] 
      for course in courses:
           try:
              
              cp = CourseProgress.objects.get(course=course)
              progress = cp.progress 

           except CourseProgress.DoesNotExist:
                progress = 0 
           courses_progress.append([course,progress]) 
           
      print("saleamlak")
      return render(request,"partials/all_dashboard.html",{'courses':courses_progress,"models": models,"tests":tests,"title":"all content"}) 
      
@login_required
def courses(request, status): 
      courses = Course.objects.all().filter(dept=request.user.department)  
      courses_progress= [] 

      if status == 'all':
          for course in courses:
               try:
               
                    cp = CourseProgress.objects.get(course=course)
                    progress = cp.progress 

               except CourseProgress.DoesNotExist:
                    progress = 0 
               courses_progress.append([course,progress]) 

      elif status == 'inprogress':
          
          for course in courses:
               try:
               
                    cp = CourseProgress.objects.get(course=course)
                    if cp.progress > 0:
                         courses_progress.append([course,cp.progress])

               except CourseProgress.DoesNotExist:
                   pass 
          
      else:
           pass 
           
      return render(request,"partials/courses.html",{'courses':courses_progress}) 
       

      
@login_required
def get_course(request,pk): 
      
      onclick_url = "fetch/course/{}/".format(pk) 
      nav_title = "modules" 
      modules = None 
      print(onclick_url) 
      try:
         course = Course.objects.get(id=pk)
         modules = course.modules.all() 
      except Course.DoesNotExist as e:
          pass 

      return render(request,"partials/modules.html",{'modules':modules,"url":onclick_url,"title":nav_title,"course_id":pk}) 
       
@login_required
def get_module(request,pk,course_id=None): 
      
      module = None 
      onclick_url = "fetch/modules/{}/".format(pk) 
      nav_title = ""
      try:
         module = get_object_or_404(Module,id=pk)
         nav_title = module.name 
      except Exception as e:
          print(" what is going on")

      return render(request,"partials/pages.html",{'module':module,"url":onclick_url,"title":nav_title,"course_id":course_id}) 

def get_page(request,pk): 
      
      page = None 
      completed = False 
      try:
         
         page = Page.objects.get(id=pk)
         completed = PageCompletion.objects.get(page=page) 
         completed = True 

      except Page.DoesNotExist:
          page = None 

      except PageCompletion.DoesNotExist:
           completed = False 

      return render(request,"partials/page.html",{'page':page,'completed':completed}) 

def alpine(request):
     
     return render(request,"partials/alpine.html",{"love":'you'})

def page_complete(request,pk,complete):
     
     print(pk,complete) 
     page = None 

     try:
           page = Page.objects.get(id=pk)  
           print(page, "oooooooooo", request.user) 
           if page is not None and complete.lower() == 'true':
                 
                 try:
                      page_complete = PageCompletion.objects.get(page=page)
                      print(page_complete)
                      print(page) 
                      print("-------------------")
                 except PageCompletion.DoesNotExist: 
                        marked = PageCompletion.objects.create(page=page, student=request.user) 
                        marked.save()
                        print("saved successs!!!!!") 

           elif page is not None and complete.lower() == 'false':
                unmark = PageCompletion.objects.filter(page=page)
                for page in unmark:
                     page.delete()  

                print("successs!! delete")

           return HttpResponse("marked")
     
     except Page.DoesNotExist:
         pass 
    
     return HttpResponse("unmarked")
                                           
import json 

def take_test_exam(request,test_id):  
        
        q = None
        next_id = None  
        finished = False 
        total_q = 0 
        try:
           test = Test.objects.get(id=test_id) 
           q = test.test.all()[0] 
           total_q = test.test.all().count() 
           next_id = 0

        except (Test.DoesNotExist,IndexError):
             q = None 
             next_id = 0 
         
        return render(request, "partials/take_test_exam.html",{'question':q,'next_id':next_id,"title":test.title,"total_q":total_q})

def course_tests(request, slug):
       
       tests = [] 
       try:
           if slug == "all_all":
               courses = Course.objects.all().filter(dept=request.user.department)
               for course in courses:
                    c_tests = Test.objects.filter(course=course)
                    for test in c_tests:
                         hard = TestQuestion.objects.filter(testExam=test,question_type="hard").all().count() or 0
                         medium = TestQuestion.objects.filter(testExam=test,question_type="medium").all().count() or 0
                         easy = TestQuestion.objects.filter(testExam=test,question_type="easy").all().count() or 0 

                         tests.append([test,course.name,{
                         "hard":hard,
                         "medium":medium,
                         "easy":easy
                         }])
           else:
               course = Course.objects.get(slug=slug)

               c_tests = Test.objects.filter(course=course)
               for test in c_tests:
                    hard = TestQuestion.objects.filter(testExam=test,question_type="hard").all().count() or 0
                    medium = TestQuestion.objects.filter(testExam=test,question_type="medium").all().count() or 0
                    easy = TestQuestion.objects.filter(testExam=test,question_type="easy").all().count() or 0 

                    tests.append([test,course.name,{
                    "hard":hard,
                    "medium":medium,
                    "easy":easy
                    }])
          

       except Course.DoesNotExist:
           return 
       print("==========================================")
       print(tests)
       return render(request,"partials/tests.html",{"tests":tests})

def exam_test_answer(request, test_id,q_id,slug):
        
        test = Test.objects.get(id=test_id)  
        try:
           q = test.test.all()[q_id]  

        except IndexError:
             q = None 
  
        try:
             
          examstatus = ExamStatus.objects.get(student=request.user,question=q)
          examstatus.response = slug
          examstatus.save() 

        except ExamStatus.DoesNotExist:
            examstatus = ExamStatus(student=request.user,question=q,response = slug)
            examstatus.save() 

        return JsonResponse({"save":True}) 

def exam_test_next_question(request, test_id,q_id):
     test = Test.objects.get(id=test_id)
     next_id = q_id + 1 
     q = None 
     finished = False  

     try:
          q = test.test.all()[next_id]

     except IndexError as e: 
          print(e)
          q = None 
          finished = True 
     
     return render(request, "partials/take_test_exam.html",{"question":q, "test_id":test_id,"next_id":next_id,"finished":finished}) 

def get_models(request,id):
     
     return render(request,"partials/model_questions.html")

def get_model_view(request,view):
     

templates/student/base.html
<!DOCTYPE html>
<html lang="en">
{% load widget_tweaks %} 
{% load static %} 

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3 style="text-align: center;">A peek into your book shelf!</h3>
    <section id="user-list">
        <h1 hx-trigger="click" hx-get="{% url 'fetch' %} "  hx-swap='outerHTML' hx-target="#users">users</h1>
       <di id="users">
           {% include 'partials/user_lists.html' %}
       </di>
       
        
    </section>

    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
</body>
</html>

templates/student/index.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> Dashboard </title>

  <!-- Google Font: Source Sans Pro -->
  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.13.7/dist/cdn.min.js"></script>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'mycss/dashboard_card.css' %}"> 
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}"> 
  

<body class="hold-transition dark-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <!-- <img class="animation__wobble" src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60"> -->
    <i class="fa fa-user-graduate fa-10x animation__wobble" style="color: #B197FC;">
         
    </i>
  </div>

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
         
         <li style="margin-left:10px">
           <h3> student dashboard </h3>
         </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fas fa-user" style="color: #ffffff;"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-lock mr-2"></i> change password 
          </a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'account:logout' %}" class="dropdown-item">
            <i class="fas fa-user mr-2"></i> Logout
          </a>
         
        </div>
      </li>
      
    </ul>
  </nav>

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
      <a href="#" class="brand-link">  
        <i class="fa fa-user-graduate fa-4x mr-2" style="color: #B197FC;"></i>
      <span class="brand-text font-weight-light"> {{request.user.username}} </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        
      </div>
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open" hx-get="/students/fetch/all/" hx-trigger="click,load" hx-target="#submain">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard 
              </p>
            </a>
            </li> 

            <li class="nav-item menu-open">
              <a href="#" class="nav-link">
                <!-- <i class="nav-icon fas fa-tachometer-alt"></i> -->
                <p>
                  courses 
  
                </p>
                <i class="right fas fa-angle-left"></i>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item" hx-get="/students/fetch/courses/all/" hx-trigger="click" hx-target="#submain">
                  <a href="#" class="nav-link">
                    <i class="nav-icon fas"></i>
                    <p>All Courses </p>
                  </a>
                </li>

                <li class="nav-item" hx-get="/students/fetch/courses/inprogress/" hx-trigger="click" hx-target="#submain">
                  <a href="#" class="nav-link">
                    <i class="nav-icon fas "></i>
                    <p>In-Progress Courses </p>
                  </a>
                </li>
              </ul>
              </li> 
          </li>
  
          <li class="nav-item menu-open">
            <a href="#" class="nav-link">
              <!-- <i class="nav-icon fas fa-tachometer-alt"></i> -->
              <p>
                Exams  

              </p>
              <i class="right fas fa-angle-left"></i>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item" hx-get="/students/fetch/models/" hx-trigger="click" hx-target="#submain">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas "></i>
                  <p>Models </p>
                </a>
              </li>

              <li class="nav-item" hx-get="/students/fetch/tests/" hx-trigger="click" hx-target="#submain">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas "></i>
                  <p>Test  </p>
                </a>
              </li>
            </ul>
            </li> 
            </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" id="submain">
   
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; SaleZHacker</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      
    </div>
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>

<!-- PAGE PLUGINS -->
<!-- jQuery Mapael -->
<script src="{% static 'plugins/jquery-mousewheel/jquery.mousewheel.js' %}"></script>
<script src="{% static 'plugins/raphael/raphael.min.js' %}"></script>
<script src="{% static 'plugins/jquery-mapael/jquery.mapael.min.js' %}"></script>
<script src="{% static 'plugins/jquery-mapael/maps/usa_states.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>

<!-- AdminLTE for demo purposes -->
<!-- <script src="{% static 'dist/js/demo.js' %}"></script> -->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard2.js' %}"></script>

<script src="{% static 'js/htmx.min.js' %}" defer></script>
<script>
  document.body.addEventListener('htmx:configRequest', (event) => {
    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
  })
  
</script>
<script src="{% static 'js/pageCompletion.js' %}">  </script> 
</body>
</html>