ExitExamPreparationPlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include 

admin.site.site_header = "Exit Exam Preparation Platform "
admin.site.site_title = "Exit Exam Preparation platform"
admin.site.index_title = "Exit Exam Preparation Platform  Admin"
from accounts.views import mylogin 

urlpatterns = [
  path("", include("home.urls")),
  path("accounts/", include(("accounts.urls",'account'),namespace='account')),
  path("accounts/", include("django.contrib.auth.urls")), 
  path('students/',include("student.urls")),
  path('instructors/',include('instructor.urls')),
  path("admin/login/", mylogin, name="login"), 
  path('admin/', admin.site.urls),
  path('ckeditor/',include('ckeditor_uploader.urls')),
  path('imagefit/', include('imagefit.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include 
from . import views  
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView,PasswordResetCompleteView

urlpatterns = [
  path("signup/", views.signup, name="signup"),
  path("logout/", views.mylogout, name="logout"), 
  path("login/", views.mylogin, name="login"),
  path("profile_edit", views.profileEdit, name="profileEdit"), 
  path("view_profile/", views.viewProfile,name="profile_view" ),
  path('password_reset/', views.ResetPasswordView.as_view(),name="password_reset"), 
  path('password_reset/done/',PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
       name="password_reset_done"),
   path('password-reset-confirm/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'),
         name='password_reset_confirm'), 
  path('password-reset-complete/',
         PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
         name='password_reset_complete'),
  path("signup/check_username/", views.check_username, name="check_username"),
   path("signup/check_email/", views.check_email, name="check_email"),
   path("signup/check_password/",views.check_password,name="check_password"), 
   
]

home/urls.py
from django.urls import path, include 
from . import views 

urlpatterns = [
   path("", views.home, name="home"),
   path("about/", views.about, name="about"), 
  
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.humanize.templatetags import humanize 
from django.forms import ModelForm 
from .manager import CustomUserManager
from EECommittee.models import Department 


class User(AbstractBaseUser, PermissionsMixin):
    USER_TYPE_CHOICES = (
        ('student','Student'),
        ('instructor','Instructor'),
        ('admin','admin'), 
    )
    user_type = models.CharField(max_length=20,choices=USER_TYPE_CHOICES,default='student') 
    first_name = models.CharField(max_length=255,null=True, blank=True) 
    last_name = models.CharField(max_length=255, null=True, blank=True) 
    username = models.CharField(max_length=255,unique=True) 
    email = models.EmailField(_("email"), unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE,related_name='users', null=True)
    avtar = models.ImageField(null=True, blank=True,upload_to='profile_picture') 
    bio   = models.CharField(max_length=255, blank=True, null=True)  
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
  
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    objects = CustomUserManager()

    def __str__(self):
        return self.username or self.email.split('@')[0]
    
    def is_admin(self):
        return self.user_type == 'admin' 
    
    def is_student(self):
        return self.user_type == 'student' 
    
    def is_instructor(self):
        return self.user_type == 'instructor' 
    
    def _get_login_date(self):

        return humanize.naturaltime(self.date_joined) 
    
    joined_date = property(_get_login_date) 

    def _get_last_seen_date(self):

        return humanize.naturaltime(self.last_login) 
    
    last_seen = property(_get_last_seen_date) 

    def _get_course_progress(self):
        from instructor.models import CourseProgress 
        completed = 0
        for cp in CourseProgress.objects.filter(student__username=self.username):
            
            if cp.progress == 100:
                completed += 1
            
        return completed 
    
    completed_course = property(_get_course_progress) 
    
    
    
class SuperUserForm(ModelForm):

    class Meta:
        model = User
        fields = "__all__"  

class NormalUserForm(ModelForm):
    
    class Meta:
        model = User 
        fields = ['username','first_name','last_name','email','department','avtar','bio']

# class Admin(User):

#     class Meta:
#         proxy = True 

# class StudentManager(models.Manager):

#     def get_queryset(self,*args,**kwargs) -> models.QuerySet:
#         return super().get_queryset(*args,**kwargs).filter(user_type='student')  
 
# class Student(User):
    
#     objects = StudentManager()
#     class Meta:
#         proxy = True 


# class InstructorManager(models.Manager):

#     def get_queryset(self,*args,**kwargs) -> models.QuerySet:
#         return super().get_queryset(*args,**kwargs).filter(user_type='instructor')  
    
    
# class Instructor(User):

#     objects = InstructorManager()
#     class Meta:
#         proxy = True 


# class Department(models.Model):
#     name = models.CharField(max_length=20, unique=True)  

#     def __str__(self):
#         return self.name 

# class Course(models.Model):
#     name = models.CharField(max_length=20) 
#     dep_id = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="courses") 
#     description = models.TextField() 
#     exitexiam_guideline = models.TextField() 
#     image = models.ImageField(upload_to="course_images") 
#     instructors = models.ForeignKey(User, on_delete=models.CASCADE, related_name="instructor") 


# class Module(models.Model):

#     name = models.CharField(max_length=255) 
#     description = models.TextField() 
#     course_id = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="modules") 
#     # instructor = models.ForeignKey(User, on_delete=models.CASCADE,related_name="instructor") 
#     created = models.DateTimeField(auto_now_add=True) 
#     updated = models.DateTimeField(auto_now=True)


# class  Section(models.Model):
#     title = models.CharField(max_length=255) 
#     notes = models.TextField() 
#     image = models.ImageField(blank=True, null=True, upload_to="section_images") 
#     created = models.DateTimeField(auto_now_add=True) 
#     updated = models.DateTimeField(auto_now=True)
#     module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name="pages") 


# class Test(models.Model):
    
#     diff_level = (
#         ('hard','hard'),
#         ('medium','medium'),
#         ('easy','easy')
#     )
#     exam_name = models.CharField(max_length=255) 
#     question = models.TextField() 
#     created = models.DateTimeField(auto_now_add=True) 
#     updated = models.DateTimeField(auto_now=True) 
#     instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="instructor") 
#     module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name="tests") 
#     difficulty = models.CharField(max_length=255, choices=diff_level)

# class ModelExam(models.Model):
    
#     diff_level = (
#         ('hard','hard'),
#         ('medium','medium'),
#         ('easy','easy')
#     )
#     exam_name = models.CharField(max_length=255) 
#     question = models.TextField() 
#     created = models.DateTimeField(auto_now_add=True) 
#     updated = models.DateTimeField(auto_now=True) 
#     instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="instructor") 
#     course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="modelExam") 
#     difficulty = models.CharField(max_length=255, choices=diff_level)
    

accounts/forms.py
from typing import Any
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from EECommittee.models import Department 
from django.conf import settings 
from django import forms 
from .models import User 
from crispy_forms.helper import FormHelper 
from crispy_forms.layout import Layout, Submit 
from django.contrib.auth.forms import AuthenticationForm 
from django.forms import ModelForm 

class SignUpForm(UserCreationForm):
    department = forms.ModelChoiceField(queryset=Department.objects.all()) 
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None
   
    class Meta:
        model = User
        fields = ["email",'username','password1','password2',"department"]
        

class LoginForm(forms.Form):
     email = forms.EmailField() 
     password = forms.CharField(widget=forms.PasswordInput) 

     

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect  
from .forms import SignUpForm, LoginForm  
from django.contrib.auth import authenticate, login ,logout
from django.urls import reverse  
from django.urls import reverse_lazy 
from django.contrib.auth.views import PasswordResetView, PasswordChangeDoneView, PasswordResetCompleteView,PasswordResetConfirmView  
from django.contrib.messages.views import SuccessMessageMixin 
from django.http import HttpResponse 
from django.contrib import messages 
from .models import User 
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.views import LoginView 

def signup(request):
    
    if request.method == 'POST':

        form = SignUpForm(request.POST) 
        
        if form.is_valid():
            form.save() 
            messages.success(request,"registration is successful") 
            return redirect(reverse("account:login"))

        else:
            print(form.errors)
            
            for error in form.errors:
               messages.error(request,form.errors[error])
           
    form = SignUpForm()
    return render(request, 'accounts/signup.html',{'form':form})
 

def mylogin(request):

    if request.method == 'POST':
        form = LoginForm(request.POST) 
        print(form) 

        if form.is_valid():
            email = form.cleaned_data['email'] 
            password = form.cleaned_data['password'] 
            user = authenticate(request, email=email,password=password) 
            if user is not None:
                if user.user_type == 'student': 
                    login(request, user) 
                    return redirect(reverse('student_dashboard')) 

                elif user.user_type == "instructor":
                    login(request, user) 
                    return redirect("/admin/") 
                elif user.is_superuser or user.user_type == 'admin':
                    login(request,user) 
                    return redirect("/admin/") 
                
            else:        
                messages.error(request,"Invalid email or password") 

        else:
             for error in form.errors:
                    messages.error(request,form.errors[error]) 
    form = LoginForm() 
    
    return render(request, 'accounts/login.html',{'form':form})

@login_required
def mylogout(request):

    if request.user.user_type == 'instructor' or request.user.user_type == 'admin' or request.user.is_superuser:
       logout(request)
       return redirect("/accounts/logout/") 
    
    else:
         return redirect("/") 
    
    
@login_required
def dashboard(request):

    return render(request, 'registration/dashboard.html', {'section':'dashboard'})

def profileEdit(request):
    pass 



def viewProfile(request):
    pass 



def check_username(request):
      username = request.POST.get('username') 
     
      if User.objects.filter(username=username).exists():
            return HttpResponse("<div id='username-error' class='error'> This username already exists </div>") 
      
      else:
           return HttpResponse("<div id='username-error' class='success'> This username is available </div>")
      
import re 
def check_password(request):
      
      progress_bar = '''
                        <div class="progress">
                           <div class="progress-bar" role="progressbar" aria-valuenow="%d" aria-valuemin="0" aria-valuemax="100">%s</div>
                       </div> 
                    '''

      digit = r'[0-9]+'
      upper = r'[A-Z]+'
      lower = r'[a-z]+' 

      password = request.POST.get('password1')

     
      if (re.search(digit, password) and re.search(upper,password) and re.search(lower,password) and len(password) > 8) or (len(password) > 10):
          return HttpResponse(progress_bar%(100,'Strong password'))  
      
      elif ((re.search(digit, password) or re.search(upper,password)) or (re.search(lower,password) or re.search(upper,password)) or (re.search(digit,password) or re.search(lower,password))) and len(password) > 8:
           return HttpResponse("<div> Medium </div>") 
      
      else:
           return HttpResponse("<div> Weak password</div>") 

def check_email(request):
      regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
      email = request.POST.get('email') 
       
      if  re.fullmatch(regex, email) :
            if User.objects.filter(email=email).exists():
                return HttpResponse("<div id='username-error' class='error'> This email already exists </div>") 
            
            else:
               return HttpResponse("<div id='username-error' class='success'> This email is available </div>")

      else:

        return HttpResponse("<div id='username-error' class='error'> Invalid email  </div>")


class ResetPasswordView(SuccessMessageMixin,PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    email_template_name = 'registration/password_reset_email.html'
    subject_template_name = 'registration/password_reset_subject'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('password_reset_done')




      
  

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap4 %} 
{% load static %} 
{% load crispy_forms_tags %}
{% load widget_tweaks %} 
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>  {% block title %} {% endblock %}   </title>
    {% bootstrap_javascript %} 
    {% bootstrap_messages %} 
    {% bootstrap_css %} 
   
    <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>

    <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'mycss/registration.css' %}" />    
</head>
<body>
      {% block content %} 

      {% endblock %}
    
    
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/index.html' %}
{% load widget_tweaks %}
{% block content %} 
<h1 class="text-center mt-5 text-primary">  <i class="fa fa-user-graduate fa-3x mx-1"></i> Login </h1>
   <div class="container mt-5">
    
    <form method="post" class="">
        {% csrf_token %}
        <div class="row  d-flex flex-column justify-content-center align-items-center mx-auto py-5 my-auto shadow-lg p-3 mb-5 bg-tertiary rounded">
            <div class="form-group">
                <div class="input-group mb-3">
                    {% render_field form.email class="form-control" placeholder="email" %}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <i class="fas fa-envelope"></i>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    {% render_field form.password class="form-control" placeholder=form.password.label %}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <i class="fas fa-lock"></i>
                        </div>
                    </div>
                </div>
                
                {% for error in field.errors %} 
                   <span class="help-block">{{error}}</span>
                {% endfor %}
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                   login 
                </button>
              </div>
             <a class="mx-2" href="{% url 'password_reset' %}"> Forgot password</a> 
              <a href="{% url 'account:signup' %}"> don't have account?</a> 
            
        </div>
       
    </form>
  
   </div>
  
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'accounts/index.html' %}
{% load widget_tweaks %}
{% block content %} 
<h1 class="text-center mt-5 text-primary"> Logout </h1>
   <div class="container mt-5">
    
        <div class="row  d-flex flex-column justify-content-center align-items-center mx-auto py-5 my-auto shadow-lg p-3 mb-5 bg-tertiary rounded">
            
               
            
        </div>
       
    
   </div>
  
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'accounts/index.html' %}
{% load widget_tweaks %} 
{% load static %}
 {% block title %} 
    signup 
 {% endblock %}

{% block content %} 
   <h1 class="mx-2 p-2 container-fluid text-center fw-bold text-primary"><i class="fa fa-user-graduate fa-3x mx-1"></i> Sign up Form </h1>
   <div class="container">
        
        <form method="post">
          <div class="row  d-flex flex-column   mx-auto py-5 my-auto shadow-lg p-3 mb-5 bg-tertiary rounded">
            {% csrf_token %} 
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label text-primary">Email address</label>
                {% render_field form.email class="form-control" placeholder="saledream8@gmail.com" hx-post="check_email/" hx-trigger='keyup' hx-target='#email' %} 
                <div id="email"></div>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label text-primary">username</label>
                {% render_field form.username class="form-control" placeholder="sale" hx-post="check_username/" hx-trigger='keyup' hx-target='#username' %} 
                <div id="username"></div> 
              </div>
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label text-primary">Password</label>
                {% render_field form.password1 class="form-control" hx-post="check_password/" hx-trigger='keyup' hx-target='#password' %} 
                <div id="password"></div>
              </div>
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label text-primary">Confirm password</label>
                {% render_field form.password2 class="form-control"  %} 
              </div>
              <div class="mb-3">
                <label for="exampleFormControlInput1" class="form-label text-primary">Department</label>
                {% render_field form.department class="form-control" placeholder="computer science" %} 
              </div>
            <div class="d-flex justify-content-around align-items-baseline">
                <button type="submit" class="btn btn-primary mt-3">sign up </button>
                <p><a href="{% url 'login' %}">sign in</a> </p>
            </div>
          </div>

        </form>
       
       
   </div>
   <script src="{% static 'js/htmx.min.js' %}" defer></script>
   <script>
     document.body.addEventListener('htmx:configRequest', (event) => {
       event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
     })
   </script>
  
{% endblock %}