ExitExamPreparationPlatform/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include 

admin.site.site_header = "Exit Exam Preparation Platform "
admin.site.site_title = "Exit Exam Preparation platform"
admin.site.index_title = "Exit Exam Preparation Platform  Admin"
from accounts.views import mylogin 

urlpatterns = [
  path("", include("home.urls")),
  path("accounts/", include(("accounts.urls",'account'),namespace='account')),
  path("accounts/", include("django.contrib.auth.urls")), 
  path('students/',include("student.urls")),
  path('instructors/',include('instructor.urls')),
  path("admin/login/", mylogin, name="login"), 
  path('admin/', admin.site.urls),
  path('ckeditor/',include('ckeditor_uploader.urls')),
  path('imagefit/', include('imagefit.urls')),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include 
from . import views 

urlpatterns = [
   path("", views.home, name="home"),
   path("about/", views.about, name="about"), 
  
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOme </title>
</head>
<body>
     {% block content %} 

     {% endblock %} 
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load bootstrap4 %} 
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  
    {% bootstrap_css %} 
    {% bootstrap_javascript %} 
    {% bootstrap_messages %} 
   

    <title>Exit Exam Preparation platform</title>

    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    
    
    <!-- Animate CSS -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet" >
    
    <!-- Owl-Carousel -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" >
    <link rel="stylesheet" href="{% static 'css/owl.theme.css' %} " >
    <link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}" >

    <!-- Custom CSS -->
    
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/home_nav.css' %}" rel="stylesheet" /> 
    <!-- Colors CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/green.css' %}">
    
    
    
    <!-- Colors CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/green.css' %}" title="green">
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/light-red.css' %} " title="light-red">
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/blue.css' %}" title="blue">
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/light-blue.css' %} " title="light-blue">
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/yellow.css' %}" title="yellow">
    <link rel="stylesheet" type="text/css" href="{% static 'css/color/light-green.css' %}" title="light-green">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    
    
    <!-- Modernizer js -->
    <script src="{% static 'js/modernizr.custom.js' %}"></script>

    
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'base.css' %}" rel="stylesheet">
    
</head>

<body class="body">
    
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>

      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col-3">
              <div class="site-logo">
                <a href="index.html" class="font-weight-bold">
                   Exit Exam Preparation platform 
                </a>
              </div>
            </div>

            <div class="col-9  text-right">
              

              <span class="d-inline-block d-lg-none"><a href="#" class="text-primary site-menu-toggle js-menu-toggle py-5"><span class="icon-menu h3 text-white"></span></a></span>


              <nav class="site-navigation text-right ml-auto d-none d-lg-block flex" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class="active"><a href="#" class="nav-link">Home</a></li>
                  <li><a href="#" class="nav-link">About</a></li>
                  <li><a href="#" class="nav-link">Contact</a></li>
                  <li>
                    <div class="account">
                      {% if request.user.is_authenticated %} 
                               <a href="#">
                                <img src="#" with="50px"/>
                               </a>
                           
                      {% else %} 
                        <a href="{% url 'account:login' %}" class="nav-link">login</a></li>
                      {% endif %}
                      
                      <a href="#" class="nav-link">sign up</li> 
                    </div>
                  </li>
                 
                </ul>
               
              </nav>
             
             
                
            </div>

           
          </div>
        </div>

      </header>


    <main>

    </main> 

    <footer>

    </footer>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>